# Change these first
owner: RocketMan
repo: KZSU-Music-Beatcheck

sites:
  - name: KZSU
    url: https://kzsu.stanford.edu/
  - name: KZSU Music
    url: https://zookeeper.stanford.edu/
  - name: KZSU Streams
    url: https://kzsu-streams.stanford.edu/
  - name: KZSU Zootopia
    url: http://kzsu.rocks/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /KZSU-Music-Beatcheck
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KZSU Music Beatcheck
  introTitle: "**KZSU Music Beatcheck** is an uptime monitor for [KZSU Music](https://zookeeper.stanford.edu/)."
  introMessage: The monitor runs every 5 minutes and will automatically open Issues for detected outages.  The response time graphs are updated 4 times per day.  The main website, the streams server, and Zootopia are also monitored for reference.
  navbar:
    - title: Status
      href: /
    - title: Zookeeper Online repo
      href: https://github.com/RocketMan/zookeeper
    - title: KZSU Music Beatcheck repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
